#!/usr/bin/python3
"output should be raise a message"
def raise_exception_msg(message=""):
    raise NameError(message)
